version: "3"

services:
  dnscrypt:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:latest
    networks:
      pihole_net:
        ipv4_address: 10.0.1.2
    expose:
      - "5300/udp"
      - "5300/tcp"
    environment:
      TZ: 'America/Denver'
    volumes:
      - './etc-dnscrypt-proxy:/config'
    dns:
      - 103.196.38.38
      - 103.196.38.39
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      pihole_net:
        ipv4_address: 10.0.1.3
      lan: {}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'America/Denver'
      WEBPASSWORD: 'ChangeMe'
      DNS1: "10.0.1.2#5300"
      DNS2: "no"
      ServerIP: 10.200.0.12
      DNSMASQ_LISTENING: all
      DNSSEC: 'true'
      VIRTUAL_HOST: pihole01.local
      WEBTHEME: default-dark
    volumes:
       - '/srv/pihole/etc-pihole/:/etc/pihole/'
       - '/srv/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 103.196.38.38
      - 103.196.38.39
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole01.local`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=web"
    depends_on:
      - dnscrypt

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
  lan:
    external: true
